============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
rootdir: /workspaces/leetcode
configfile: setup.cfg
collected 43 items / 1 error
run-last-failure: 1 known failures not in selected tests

==================================== ERRORS ====================================
____ ERROR collecting leetcode/palindrome-number/test_palindrome_number.py _____
ImportError while importing test module '/workspaces/leetcode/leetcode/palindrome-number/test_palindrome_number.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/vscode/.pyenv/versions/3.10.12/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
leetcode/palindrome-number/test_palindrome_number.py:2: in <module>
    from array.palindrome_number import Solution
E   ModuleNotFoundError: No module named 'array.palindrome_number'; 'array' is not a package
------------- generated xml file: /workspaces/leetcode/pytest.xml --------------
=========================== short test summary info ============================
ERROR leetcode/palindrome-number/test_palindrome_number.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.06s ===============================
