============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
rootdir: /workspaces/leetcode
configfile: setup.cfg
collected 47 items
run-last-failure: no previously failed tests, not deselecting items.

leetcode/divide-two-integers/test_divide_two_integers.py .............
leetcode/integer-to-roman/test_integer_to_roman.py ...........
leetcode/palindrome-number/test_palindrome_number.py ......
leetcode/remove-duplicates-from-sorted-array/test_remove_duplicates_from_sorted_array.py F.....
leetcode/roman-to-integer/test_roman_to_integer.py ...........

=================================== FAILURES ===================================
________________ test_removeDuplicates[nums0-0-expected_nums0] _________________

nums = [], expected_result = 0, expected_nums = []

    @pytest.mark.parametrize(
        ('nums', 'expected_result', 'expected_nums'),
        [
            ([], 0, []),
            ([1, 1, 2], 2, [1, 2]),
            ([0, 0, 1, 1, 1, 2, 2, 3, 3, 4], 5, [0, 1, 2, 3, 4]),
            ([1, 2, 3], 3, [1, 2, 3]),
            ([1, 1, 1, 1], 1, [1]),
            ([1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5], 5, [1, 2, 3, 4, 5]),
        ],
    )
    def test_removeDuplicates(
        nums: List[int],
        expected_result: int,
        expected_nums: List[int],
    ):
        solution = Solution()
        result = solution.removeDuplicates(nums)
>       assert result == expected_result
E       assert 1 == 0

leetcode/remove-duplicates-from-sorted-array/test_remove_duplicates_from_sorted_array.py:25: AssertionError
------------- generated xml file: /workspaces/leetcode/pytest.xml --------------
=========================== short test summary info ============================
FAILED leetcode/remove-duplicates-from-sorted-array/test_remove_duplicates_from_sorted_array.py::test_removeDuplicates[nums0-0-expected_nums0]
========================= 1 failed, 46 passed in 0.06s =========================
